@base_rul=http://localhost:3000

POST http://localhost:3000/clientes
Content-Type: application/json

{
    "fullName": "John Doe",
    "birthDate": "2000/05/12",
    "document": "07242927560"
}
###

GET http://localhost:3000/clientes/01936623-f68a-75cd-9641-dc007a41c4e7
Content-Type: application/json


###