services:
  postgres:
    container_name: MockBank.Postgres
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/Postgres/.docker:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mock_bank
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d mock_bank']
      interval: 5s
      retries: 5
      start_period: 1s
      timeout: 10s
  api:
    container_name: MockBank.Api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: mock_bank
      DATABASE_USER: root
      DATABASE_PASSWORD: root
